### ISSUE TITLE
value error with the design matrix in Lmer.py

### ISSUE THREAD

**Issue by sbSHA** [ejolly/pymer4#107]
Hi, 
I got this error when I am running Lmer for fitting the model. I dont know if anyone else has faced this issue. I think it's a small bug? 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [9], in <cell line: 50>()
     47 df_sub = df[["a1", "a2", "b1", "b2", "c1", "c2", "c3", "event_id", "station", "lnY"]]
     49 model = Lmer('lnY ~ 1 + a1 + a2 + b1 + b2 + c1 + c2 + c3 +(1|event_id)+(1|station)', data = df_sub)
---> 50 model.fit(summarize = True)

File ~/opt/anaconda3/envs/KikNet/lib/python3.8/site-packages/pymer4/models/Lmer.py:444, in Lmer.fit(self, conf_int, n_boot, factors, permute, ordered, verbose, REML, rank, rank_group, rank_exclude_cols, no_warnings, control, old_optimizer, **kwargs)
    442 # Store design matrix and get number of IVs for inference
    443 design_matrix = stats.model_matrix(self.model_obj)
--> 444 if design_matrix:
    445     self.design_matrix = pd.DataFrame(base.data_frame(design_matrix))
    446     num_IV = self.design_matrix.shape[1]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by ejolly** [comment]
@sbSHA Looks like you're using an older version of pymer4 (~0.7.2). This has been fixed in more recent versions. Please try updating.
