### ISSUE TITLE
Problem in installing pymer4

### ISSUE THREAD

**Issue by amirt1994** [ejolly/pymer4#108]
Dear Developer,

I am using python 3.7. I tried to install pymer4 (using method 2 installation) on my windows 10.
After testing installation I came up with following error:

Error! The R package "lmerTest" is not installed.

Then I installed lmertest using "conda install -c conda-forge r-lmerTest". 
After I tested pymer4 installation again I came up with the same error!
without this package I cant run my code, if you know any solution please let me know!

Regards,
Amir

**Comment by ejolly** [comment]
Can you please use the issue template [here](https://github.com/ejolly/pymer4/issues/new?assignees=&labels=bug&template=bug_report.md&title=Issue+with...) which will allow you to provide more detail?
