### ISSUE TITLE
Add option to set seed when boostrapping

### ISSUE THREAD

**Issue by dramanica** [ejolly/pymer4#115]
For repeatability, it would be good to be able to set the seed for `Lmer.confint()` (as it is possible in `lme4` for `confint` and `bootMer`). 
@ejolly I have a patch implementing this option with the relevant unit test, and I can make a pull request. Against which branch do you want it? `dev` is currently slightly behind `master`, so should use `master` as reference?

**Comment by ejolly** [comment]
Sounds good, yup `master` works, that way I can merge it in more quickly. Still need to do some work to clean things up and bring `dev` up to speed

**Comment by dramanica** [comment]
Ok, pull request #116 against master.
