### ISSUE TITLE
Simple slopes and differences in simple slopes for continuous x categorical interactions LMER

### ISSUE THREAD

**Issue by shanaadise** [ejolly/pymer4#121]
I did not want to comment on the enhancement  so I will write my comment here (in case it was already implemented).

For context, here I want to generate posthoc tests for a continuous x categorical interaction and estimate simple slopes (via marginal estimates) and differences of simple slopes (e.g., comparisons) like in this example below. I believe that when there is a continuous x categorical interaction, pymer calls emtrends. Yet, I am struggling to understand the output of this, and want to know if there is a way to get the estimates for levels of the continuous variable (e.g., -1, 0, +1 SD of the mean). My comment before referenced just the plotting mechanism but here, I would like to have the estimates for interpretation beyond a figure. I know that there is a new release 0.8.0, which I tried to upgrade to but I had too many compiler issues with rpy2 that I downgraded to Pymer 0.7.6. However, I do not think this was implemented in 0.8.0 unless you can point me into the right direction. 

Here is my code: 

```
formula =  'bmi~time* smri_vol_scs_aal + (1|mri_info_deviceserialnumber/src_subject_id)'

model = Lmer(formula, data=drun)

## here the contrast is -1 for baseline so that is a reference. 
model_fit = model.fit(factors={'time' : {"0":-1, "2":1 }},REML=False)

marginal_estimates, comparisons = model.post_hoc(marginal_vars=["time"], grouping_vars=["smri_vol_scs_aal"], p_adjust="bonf")

```

This gives me the following output for the marginal estimates (simple slopes) and differences of simple slopes (comparisons), I presume. However, I would like to test the difference in simple slopes for various bins of the continuous IV (e.g., Time 0 at -1SD,0,+1SD of the variable 'smri_vol_scs_aal' and Time 2 at the same:

```
time	smri_vol_scs_aal	Estimate	2.5_ci	97.5_ci	SE	DF
0	0	-0.0	16.951	16.867	17.035	0.041	29.393
1	2	-0.0	18.712	18.622	18.801	0.044	39.149




Contrast | smri_vol_scs_aal | Estimate | 2.5_ci | 97.5_ci | SE | DF | T-stat | P-val | Sig
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
time0 - time2 | -0.0 | -1.76 | -1.822 | -1.699 | 0.031 | 2716.131 | -55.919 | 0.0 | ***


```

This is the figure showing my interaction for which I want to estimate the effects
![Accumbens area L_x_Time_on_BMI_2023-04-19](https://user-images.githubusercontent.com/13022146/235016184-1e9ece26-d6ca-41bd-899d-f97480c846c0.png)

**Comment by ejolly** [comment]
Hi again @shanaadise 

Yup your interpretation of the outputs you're seeing is correct: simple slopes and the difference in simple slopes. But If you want to estimate what I think you do, then you shouldn't be treating `time` as a factor, but rather the `smri_vol_scs_aal` variable which looks to have 3 levels (smaller, medium, and larger). The interaction effect is then the change in slope of the relationships between time and bmi across each level of `smri_vol_scs_aal`.

Unfortunately `pymer4` doesn't support more complicated simple-effect estimation that `emtrends` might (not sure) such as different quartiles/SDs of a continuous variable. You could always manually create a *new* categorical variable called something like "time_bins" that groups together observations at different values of time (e.g. 0-.75, .75-1.25, 1.25-2) and then run a new model with 2 categorical factors to estimate something similar.
