### ISSUE TITLE
Make pymer compatible with most recent python version? 

### ISSUE THREAD

**Issue by JohannesWiesner** [ejolly/pymer4#122]
Hi, based on this stackoverflow post:

https://stackoverflow.com/questions/76858353/possibility-to-trace-back-which-packages-hinder-conda-from-installing-most-recen/76860981#76860981

It seems that pymer hinders conda from installing python 3.11. Are there any plans to update the package, so python 3.11 is posssible?

**Comment by JohannesWiesner** [comment]
Ah, I see - [there's already an issue on that](https://github.com/conda-forge/staged-recipes/pull/22346).

**Comment by ejolly** [comment]
hey @JohannesWiesner I just released 0.8.1 which now supports Python 3.8-3.11. Sorry about that!

**Comment by JohannesWiesner** [comment]
Much appreciated, thanks a lot! ❤️
