### ISSUE TITLE
How to specify the number of decimal places in model.fit()

### ISSUE THREAD

**Issue by psyMingzheZhang** [ejolly/pymer4#131]
Hello everyone, I recently found that when using pymer4.models.Lmer, the results obtained with model.fit are limited to three decimal places at most. I wonder if there is a way to retain more decimal places in these results :-) ?

**Comment by ejolly** [comment]
Hi @psyMingzheZhang yup! The output of fit rounds to 3 decimal places, but if you inspect the coefficients on a fitted model, they're just pandas data frames with no rounding: .coefs, .fixef, .ranef

**Comment by psyMingzheZhang** [comment]
Hi @ejolly, thank you for your response! The reason I asked this question is because I need to perform multiple comparisons correction on p-values. For example, I have 1000 voxels that need correction, and if I use Bonferroni correction, a p-value of 0.0004 may not pass the correction. However, if rounded to three decimal places, it becomes 0 and would pass the correction. Is there a solution to this?  By the way, the pymer4 package is very useful :-）Wishing you a Merry Christmas holiday!

**Comment by psyMingzheZhang** [comment]
> Hi @psyMingzheZhang yup! The output of fit rounds to 3 decimal places, but if you inspect the coefficients on a fitted model, they're just pandas data frames with no rounding: .coefs, .fixef, .ranef

Hi @ejolly, thank you for your response! The reason I asked this question is because I need to perform multiple comparisons correction on p-values. For example, I have 1000 voxels that need correction, and if I use Bonferroni correction, a p-value of 0.0004 may not pass the correction. However, if rounded to three decimal places, it becomes 0 and would pass the correction. Is there a solution to this? By the way, the pymer4 package is very useful :-）Wishing you a Merry Christmas holiday!

**Comment by ejolly** [comment]
Happy holidays and new year to you too @psyMingzheZhang ! I would definitely use the un-rounded values (by accessing the `model.coefs` or `model.marginal_coefs` or `model.marginal_contrasts if calling `model.post_hoc()`) prior to performing multiple comparisons correction. Using your example a p-value of .0004 would survive bonferonni correction for 1000 tests (1/1000 = .001 > .0004).
