### ISSUE TITLE
Issues with degrees of freedom of my lmer model. 

### ISSUE THREAD

**Issue by cameron-mccabe** [ejolly/pymer4#133]
For some reason, when I model my variables the degrees of freedom are not giving the expected value: 
E.g.:  (Intercept) DF = 14.914
         init_acc DF = 12525.310
The number of observations is 12538, so the DF should be 12536 for both (Intercept) and init_acc. 

What is strange is when I z-score my variables within participants (this is a repeated-measures study), the DF is 12536 for both (Intercept) and init_acc. 
What is going?

**Comment by ejolly** [comment]
Will direct future users to lmertest docs as we simply wrap their implementation: https://cran.r-project.org/web/packages/lmerTest/lmerTest.pdf
