### ISSUE TITLE
ImportError on lmer

### ISSUE THREAD

**Issue by samuelmull** [ejolly/pymer4#135]
(sorry to mess up the structure a bit, for the installation into the 4 different clean test_env, see end of section 1. Description)

## 1. Description
- I installed pymer4 into an existing environment today by following [the guide on installing via Anaconda](http://eshinjolly.com/pymer4/installation.html#using-anaconda-recommended). 
- Trying to import lmer by `from pymer4.models import lmer` raises `ImportError: cannot import name 'lmer' from 'pymer4.models'`
- If I instead run `from pymer4 import models` (which does not give an error) and then try to run a model by `model = models.lmer.lmer('accuracy ~ mask * eeg_data + position (1|subjID)', data = df, family = 'binomial')` raises `AttributeError: module 'pymer4.models' has no attribute 'lmer'`
- My guess is that it is some kind of circular import dependency, but I cannot wrap my head around that as a concept. I'm quite new to coding. Sorry. 

### Anything I tried to solve the issue.
- First, I tried installing pymer4 into an existing environment, which lead to the error described above. 
- I then created and installed into a new environment, using `conda create --name pymer4 -c ejolly -c conda-forge -c defaults pymer4`, with the same result.
- Then I installed pmer4 into the 4 clean test_env described in the guidelines, with the same error occurring every time.

### Installing into a clean environment, as outlined by the issue guidelines
For all of these, I followed the same procedure as in the section on minimal reproducible example below, which includes installing spyder into the env. I do not know how to test for the issue without spyder.  Sorry about that.

1. `conda create --name test_env1 -c ejolly -c defaults -c conda-forge pymer4` - same error
2. `conda create --name test_env2 -c ejolly -c conda-forge -c defaults pymer4` - same error
3. `conda create --name test_env3 -c ejolly/label/pre-release -c defaults -c conda-forge pymer4` - same error
4. `conda create --name test_env4 -c ejolly/label/pre-release -c conda-forge -c defaults pymer4` - same error

## 2. Minimal reproducible example
in MATE terminal:
`conda create --name pymer4 -c ejolly -c conda-forge -c defaults pymer4`
`conda activate pymer4`
`conda install spyder`
`spyder`

in spyder:
`from pymer4.models import lmer`
I **only** run this line in spyder, nothing else. No packages have been imported before running this line. Spyder has just been started.

which gives the output:
` Cell In[1], line 1`
`  from pymer4.models import lmer`

`ImportError: cannot import name 'lmer' from 'pymer4.models' (/home/testuser/miniconda3/envs/pymer4/lib/python3.11/site-packages/pymer4/models/__init__.py)`

## 3. Conda environment
[pymer4_issue.txt](https://github.com/ejolly/pymer4/files/14510132/pymer4_issue.txt)

## 4. System information
```
$  uname -mprsv
Linux 5.4.0-172-generic #190-Ubuntu SMP Fri Feb 2 23:24:22 UTC 2024 x86_64 x86_64

$  cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by ejolly** [comment]
@samuelmull You're going to hate this.... because I saw your extensive write up in  [this issue](https://github.com/Neuroling/SPINCO_SINEEG/issues/4) and I know the pain of getting lmms to work in python over the years...

But you were just experiencing a syntax issue. Models in `pymer4` follow Python class conventions and so are *capitalized*: `Lmer` not `lmer`

This works: `from pymer4.models import Lmer`  

This won't `from pymer4.models import lmer`
