### ISSUE TITLE
Suppress printing

### ISSUE THREAD

**Issue by arose13** [ejolly/pymer4#20]
I was wondering if I could make a PR with a verbose flag in `.fit()` that turns this `print("Fitting linear model using...` on and off.

I'm making 100,000's of calls to this function and I think it would be better not to print this.

**Comment by ejolly** [comment]
Sure thing! If you make the PR I can review it

**Comment by arose13** [comment]
PR is there for review whenever

https://github.com/ejolly/pymer4/pull/21

**Comment by ejolly** [comment]
Added in #21
