### ISSUE TITLE
Question about fixef, ranef, and coefs

### ISSUE THREAD

**Issue by chnynf** [ejolly/pymer4#26]
Hi ejolly, thanks for the project. I've been running mixed effect logistic regression in python and this library is really helpful. I have one question about the outputs:

Seems like mode.fixef actually refers to the coef(model) in R. Model.coefs refers to the output in the summary(model) in R, which is correspondent to fixef(model) in lme4. Wanted to confirm that.

**Comment by ejolly** [comment]
Thanks! Yup that's correct. My terminology varies from the syntactic naming in R to be instead more consistent with language in the statistical literature broadly speaking (at least I think so). The reason for that is `model.fixef` is the cluster-level (e.g. subject) fixed effects coefficients hence it made sense to name it that way, where as `model.ranef` is the deviation for each cluster from the overall group model coefficients (i.e. `model.coefs - model.fixef  = model.ranef`).

**Comment by chnynf** [comment]
Got it. The outputs are pretty intuitive, but just wanted to confirm. Thanks!
