### ISSUE TITLE
[joss-review] Installation instructions

### ISSUE THREAD

**Issue by janfreyberg** [ejolly/pymer4#28]
I just tried to install this and failed `brew install gcc` installed `gcc-8` rather than `gcc-7`.

Is it possible to fix the recommend bash command that sets the CC environment variable to use either?

Also, it may make sense to provide conda specific installation instructions: for users with no R installation, installing `rpy2` from conda-forge is likely the most frictionless way of installing R; by the looks of it, lmerTest and lsmeans are also on conda-forge.

If you're not so familiar with conda I can take a stab at that.

**Comment by ejolly** [comment]
@janfreyberg Yup I can work on editing the environment variable command. I'd love some help on getting R and rpy2 as well as the r package dependencies from conda-forge if you already have experience setting that up during installation!

**Comment by janfreyberg** [comment]
Having just tested this, there seem to be dependency conflicts at the moment - rpy2 2.8.5 on conda forge depends on r=3.3.2, which at least on conda-forge is listed as incompatible with r-lmertest. Might depend on #25 being fixed or the r-lmertest conda-forge package being updated.

**Comment by ejolly** [comment]
So I made a few fixes that should make `pymer4` compatible with `rpy 2.9.x`. Any chance you can try again with the latest version from github? One installation issue I'm not certain about, and would be happy to receive any advice on, is the following:

The latest versions of `rpy2` (i.e. `>=2.9.x`) don't support Python 2. Therefore in order for `pymer4` to remain both Python 2 and 3 compatible, it seems like I have to freeze the requirements to an older version as I'm doing currently. However, if overall installation becomes easier by dropping Python 2 support and using `conda-forge` to install latest rpy2 and all R-package dependencies then maybe that's ultimately more convenient for users. Thoughts?
