### ISSUE TITLE
[joss-review] Paper issues

### ISSUE THREAD

**Issue by janfreyberg** [ejolly/pymer4#29]
A few minor issues with the paper:

- [x] in the example, `get_resource_path` is never defined, I believe you're missing the import statement `from pymer4.utils import get_resource_path`
- [x] the line `model.plot('IV2')` from your paper throws a NotImplementedError
- [x] replace `langauge` with `language` in the first paragraph
- [x] references have no DOIs

**Comment by ejolly** [comment]
Ok these should all be fixed in the latest commit. I removed the `model.plot()` call since that specifically applies to continuous predictors only (for the time being). I've added DOIs for every source I could find but some don't appear to have any.
