### ISSUE TITLE
Empty models with pymer4 to calculate the ICC

### ISSUE THREAD

**Issue by gmmaio94** [ejolly/pymer4#39]
How can I specify an empty model using pymer4 ? 

The R lme4 version of the empty model I am talking about is this: "target ~ 1 + (1|group)" . No features; just the target, the fixed intercept, and the random intercept. This will allow to calculate the Intra-Class Correlation.

I have tried the following specifications on pymer4
 1) "target ~ 1 + (1|group)"
2)  "target ~ 0 + (1|group)"
3)  "target ~  (1|group)"
4)  "target ~  dummyIntercept + (1|group)" , where dummyIntercept is a variable with a fixed value of 1 for all the cases. 

The error I get is the following:

"Error in names(x) <- value : 
  'names' attribute [2] must be the same length as the vector [1]" 

Any help with this would be greatly appreciated. 

Thanks so much,
Giuseppe

**Comment by ejolly** [comment]
Thanks for moving this discussion here @gmmaio94. I can't seem to reproduce your error. See my example notebook [here](https://nbviewer.jupyter.org/urls/dl.dropbox.com/s/o18pz1z8asvngq1/ICC_model_demo.ipynb).  

Can you share a reproducible example e.g. with your data or a subset of it, or replicating my example notebook? Can you also make sure you're using the latest version of pymer4 (master branch on github, but the pip package should match that).

You can also try installing the [development branch](https://github.com/ejolly/pymer4/tree/dev):  
`pip install git+https://github.com/ejolly/pymer4.git@dev` and see if that works for you, but testing both the master and development branches doesn't produce the error for me.

**Comment by gmmaio94** [comment]
Hi @ejolly,
Thanks for your response. I have installed the development branch, and got the same error. 

Please note that my model has a binary outcome: I am carrying out a multi-level logistic regression.Perhaps this might be the issue ? My code is below:

model0 = Lmer('target ~ (1|group)', 
          data = df,
          family = 'binomial')

model0.fit()

 Unfortunately, I cannot share the data as it is confidential.   

Thanks again for your help. 
G.

**Comment by ejolly** [comment]
Ah I see, the `family='binomial'` was key to me reproducing this. Thanks for clarifying @gmmaio94. For now, you can use the [null_model_fix](https://github.com/ejolly/pymer4/tree/null_model_fix) branch I just added, which works for binomial models, but I haven't yet verified it works with other distribution families (e.g. poisson). 

To track a _complete_ fix, I've opened this PR https://github.com/ejolly/pymer4/pull/40

**Comment by gmmaio94** [comment]
Fantastic !
It works now, thanks so much. 
Have a great day,
G.

**Comment by ejolly** [comment]
Fixed in upcoming release
