### ISSUE TITLE
AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'

### ISSUE THREAD

**Issue by yanst001** [ejolly/pymer4#42]
Hi, I am testing basic usage code from http://eshinjolly.com/pymer4/usage.html 

```
model = Lmer('DV ~ IV2 + (IV2|Group)',data=df)
model.fit()
```
and get `AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'` , though there is no issue when running Lm on top of modular`from pymer4.models import Lm, Lmer`

I am using rpy2=3.0.5, R version 3.6.0, and Python 3.6.5 (pandas 0.23.1) on the operating system used: MacOS Mojave 10.14.6. Are there any versions listed need update?

**Comment by Shotgunosine** [comment]
I think this package is currently only working with rpy2 <3. I've had good luck with 2.9.4.

**Comment by ejolly** [comment]
Closing this because these issues should be mostly fixed in the latest release (0.7.0)
