### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'copy'

### ISSUE THREAD

**Issue by jprice80** [ejolly/pymer4#43]
I'm not sure if this is an error or just a misunderstanding on my part.  Is there a limitation for permute that primarily requires continuous independent variables?  The following corresponds to a split plot repeated measures ANOVA which contains all categorical measures. When running the code below using all categorical measures, I get the error: 

AttributeError: 'DataFrame' object has no attribute 'copy'

import os
import pandas as pd
import seaborn as sns
from pymer4.models import Lm, Lmer
from pymer4.utils import get_resource_path
import pymer4

dat = pd.read_csv('C:/Dropbox/Codes/Repeated Measures ANOVA/R/HeartRate.csv', index_col='Obs')

drugs=list(dat['drug'].unique())
times=list(dat['time'].unique())
patients=list(dat['patient'].unique())

model = Lmer('HR ~ drug + time + drug:time + (1|drug:patient)',data=dat)
model.fit(factors={"drug": drugs, 
                   "time": times,
                   "patient": patients}, permute=1000)

model.anova(force_orthogonal=True)

[HeartRate.zip](https://github.com/ejolly/pymer4/files/3520694/HeartRate.zip)

**Comment by ejolly** [comment]
@jprice80 Please try using a the latest release version 0.7.0 as see if you run into the same issues. Lots of bug fixes and compatibility updates that I think should solve your problem
