### ISSUE TITLE
Error in the random effect cheat sheet

### ISSUE THREAD

**Issue by benwhalley** [ejolly/pymer4#53]
Hi, I think there is a mistake in the random effects cheat sheet here:
http://eshinjolly.com/pymer4/rfx_cheatsheet.html#

Specifically, the double bar notation is actually for removing correlated random effects. It's not relevant whether the predictor is a factor or continuous. See page 7 here:
https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf

**Comment by ejolly** [comment]
Thanks for the updated info! I recall in past of `lme4` versions `||` didn't work unless the predictor was continuous, but maybe that's changed? Either way I'll update the docs when I get a chance

**Comment by ejolly** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation updates](https://trello.com/c/pvp8cGHL/10-documentation-updates)
