### ISSUE TITLE
Add logistic regression

### ISSUE THREAD

**Issue by ejolly** [ejolly/pymer4#54]
It would be great to add this without making sklearn a dependency...not sure if that's avoidable or not

**Comment by ejolly** [comment]
Moved to Trello

**Comment by jpgerber** [comment]
Hi, has logistic regression been added to pymer4 yet, please?

**Comment by ejolly** [comment]
Hi @jpgerber unfortunately not yet. It may happen but currently it's a long-term goal because it would require a custom implementation to avoid adding `sklearn` as a dependency: https://trello.com/c/HLgqBhqm

Happy to take pull requests!
