### ISSUE TITLE
Encountering issues running family != 'gaussian' for lmer

### ISSUE THREAD

**Issue by sandy1729-swish** [ejolly/pymer4#66]
I have been using your lmer package (thank you!) but I don't seem to be able to get any of the other families to run. I get this error, no matter what family= value I try (aside from gaussian, which works fine).

If you want to look into it further, I can probably find a way to send you a csv for the data so you can try it yourself.

Sandy Weil

Here is my model specification:
model  = Lmer('count_int ~ 0 + cat01 + cat02 + cat03 + cat04 + cat05 + (1|u1) + (1|u2) + (1|u3)', data=df ,family='poisson')

---------------------------------------------------------------------------
RRuntimeError                             Traceback (most recent call last)
<ipython-input-46-1f8f6deb6893> in <module>
----> 1 print(model_poisson.fit())

/usr/local/lib/python3.7/site-packages/pymer4/models/Lmer.py in fit(self, conf_int, n_boot, factors, permute, ordered, summarize, verbose, REML, rank, rank_group, rank_exclude_cols, no_warnings, control, old_optimizer)
    383                 pdb.set_trace()
    384                 _fam = self.family
--> 385             lmc = robjects.r(f"glmerControl({control})")
    386             self.model_obj = lmer.glmer(
    387                 self.formula, data=dat, family=_fam, REML=REML, control=lmc

/usr/local/lib/python3.7/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    196                 kwargs[r_k] = v
    197         return (super(SignatureTranslatedFunction, self)
--> 198                 .__call__(*args, **kwargs))
    199 
    200 

/usr/local/lib/python3.7/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    123             else:
    124                 new_kwargs[k] = conversion.py2rpy(v)
--> 125         res = super(Function, self).__call__(*new_args, **new_kwargs)
    126         res = conversion.rpy2py(res)
    127         return res

/usr/local/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py in _(*args, **kwargs)
     42 def _cdata_res_to_rinterface(function):
     43     def _(*args, **kwargs):
---> 44         cdata = function(*args, **kwargs)
     45         # TODO: test cdata is of the expected CType
     46         return _cdata_to_rinterface(cdata)

/usr/local/lib/python3.7/site-packages/rpy2/rinterface.py in __call__(self, *args, **kwargs)
    619                     error_occured))
    620             if error_occured[0]:
--> 621                 raise embedded.RRuntimeError(_rinterface._geterrmessage())
    622         return res
    623 

RRuntimeError: Error in (function (formula, data = NULL, family = gaussian, control = glmerControl(),  : 
  unused argument (REML = TRUE)

**Comment by yingboli** [comment]
@ejolly I think this is because the `glmer` function in `lme4` doesn't take the `REML` argument. Here's my fix on how to proposal (it worked in my fork, but for some reason, I cannot submit a pull request)
https://github.com/yingboli/pymer4/commit/8e02dc520cad2f514c54abc30bf918809cf0005e
https://github.com/yingboli/pymer4/commit/a53dec33500581b3ff6b5d62ddfeed1254a4dc47

**Comment by ejolly** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug fixes](https://trello.com/c/t3UDNQMg/7-bug-fixes)

**Comment by ejolly** [comment]
Thanks for the quick catch @yingboli! Not sure why you can't make a PR, but I've incorporated your fixes into the dev branch and they'll be applied in the upcoming release

**Comment by sandy1729-swish** [comment]
Awesome. Thanks to you both.

**Comment by sandy1729-swish** [comment]
btw, I put Yingbo's changes into my local copy of the code and reran my
model. I can confirm that it did fix the issue for me.
