### ISSUE TITLE
error while importing pymer4

### ISSUE THREAD

**Issue by chpriya03** [ejolly/pymer4#69]
ImportError                               Traceback (most recent call last)
<ipython-input-6-43564a4498bb> in <module>
----> 1 import pymer4

~\Anaconda3\lib\site-packages\pymer4\__init__.py in <module>
      3 __all__ = ["models", "utils", "simulate", "stats", "io", "__version__"]
      4 
----> 5 from .models import Lmer, Lm, Lm2
      6 from .simulate import easy_multivariate_normal, simulate_lm, simulate_lmm
      7 

~\Anaconda3\lib\site-packages\pymer4\models\__init__.py in <module>
      3 """
      4 
----> 5 from .Lmer import Lmer
      6 from .Lm import Lm
      7 from .Lm2 import Lm2

~\Anaconda3\lib\site-packages\pymer4\models\Lmer.py in <module>
     10 import rpy2.robjects as robjects
     11 from rpy2.robjects import pandas2ri
---> 12 from rpy2 import rinterface_lib
     13 import warnings
     14 import numpy as np

ImportError: cannot import name 'rinterface_lib' from 'rpy2' (C:\Users\chpri\Anaconda3\lib\site-packages\rpy2\__init__.py)

**Comment by ejolly** [comment]
Sorry about that @chpriya03, there's a heavy updated release coming out soon that should solve several different installation issues including yours, but it's still in the works. You can try installing from the development branch and see if that works for you:

`pip install git+https://github.com/ejolly/pymer4.git@dev`

**Comment by chpriya03** [comment]
Still facing the same issue, I need this package working for my final year master project. Any help will be appreciated.
Thank you.

**Comment by ejolly** [comment]
Can you provide some info about what version of `rpy2` and `pandas` you're using?  Also did you install manually or through Anaconda?

**Comment by chpriya03** [comment]
The rpy2 version is 2.9.4 and panda version is 1.0.5 and I tried installing through anaconda

**Comment by ejolly** [comment]
Ah it might be that your version of rpy2 has an issue. Can you try upgrading it? See if you can get a version >= 3.1 via conda: `conda update rpy2`. If it doesn't find an upgraded version you'll need to use conda forge: `conda update rpy2 -c conda-forge`.

**Comment by chpriya03** [comment]
After updating to rpy2 to version 3.3.2 now I am facing a new error 

OSError                                   Traceback (most recent call last)
<ipython-input-3-43564a4498bb> in <module>
----> 1 import pymer4

~\Anaconda3\lib\site-packages\pymer4\__init__.py in <module>
      3 __all__ = ["models", "utils", "simulate", "stats", "io", "__version__"]
      4 
----> 5 from .models import Lmer, Lm, Lm2
      6 from .simulate import easy_multivariate_normal, simulate_lm, simulate_lmm
      7 

~\Anaconda3\lib\site-packages\pymer4\models\__init__.py in <module>
      3 """
      4 
----> 5 from .Lmer import Lmer
      6 from .Lm import Lm
      7 from .Lm2 import Lm2

~\Anaconda3\lib\site-packages\pymer4\models\Lmer.py in <module>
      7 
      8 from copy import copy
----> 9 from rpy2.robjects.packages import importr
     10 import rpy2.robjects as robjects
     11 from rpy2.rinterface_lib import callbacks

~\Anaconda3\lib\site-packages\rpy2\robjects\__init__.py in <module>
     14 from functools import partial
     15 import types
---> 16 import rpy2.rinterface as rinterface
     17 import rpy2.rlike.container as rlc
     18 

~\Anaconda3\lib\site-packages\rpy2\rinterface.py in <module>
      4 import typing
      5 from typing import Union
----> 6 from rpy2.rinterface_lib import openrlib
      7 import rpy2.rinterface_lib._rinterface_capi as _rinterface
      8 import rpy2.rinterface_lib.embedded as embedded

~\Anaconda3\lib\site-packages\rpy2\rinterface_lib\openrlib.py in <module>
     42     rlib = _rinterface_cffi.lib
     43 else:
---> 44     rlib = _dlopen_rlib(R_HOME)
     45 
     46 

~\Anaconda3\lib\site-packages\rpy2\rinterface_lib\openrlib.py in _dlopen_rlib(r_home)
     35         raise ValueError('The library path cannot be None.')
     36     else:
---> 37         rlib = ffi.dlopen(lib_path)
     38     return rlib
     39 

OSError: cannot load library 'C:\Users\chpri\Anaconda3\lib\R\bin\x64\R.dll': error 0x7e

**Comment by ejolly** [comment]
Hmm unfortunately this looks an `rpy2` installation issue trying to find and connect to your R kernel rather than a `pymer4`issue. I might try setting up a fresh environment with Anaconda and installing everything within there and seeing if that helps:

`conda create --name newenv -c conda-forge python>=3.7 r-base r-lme4 r-lmerTest r-emmeans`  
`conda activate newenv`
`pip install git+https://github.com/ejolly/pymer4.git@dev`

Other than that I'm not sure I can be more helpful since I don't have access to a Windows machine. You might try bringing this issue up on the `rpy2` github repo because it looks like `rpy2` is not working for you at all.

**Comment by chpriya03** [comment]
Thanks for the help, but still facing the same issue. I have reported this issue on rpy2 github repo.

**Comment by ejolly** [comment]
Ok, I'm going to close this in that case. Feel free to open if you get any words of wisdom that other Windows users might benefit from. Apologies again
