### ISSUE TITLE
ratchet up Python versions in the CI?

### ISSUE THREAD

**Issue by turbach** [ejolly/pymer4#85]
Hi Eshin, any chance you could try adding Python 3.9 to the CI build matrix at some point?

I've been testing our other conda packaging CI with 3.9, so far so good.

Also I see where the minimum Python version for h5py is now 3.7 ([h5py 3.2 breaking changes](https://docs.h5py.org/en/stable/whatsnew/3.2.html#breaking-changes-deprecations)).  So the same goes for deepdish, might consider whether to keep the 3.6 CI job for future releases.

Tom

**Comment by ejolly** [comment]
Fixed in https://github.com/ejolly/pymer4/commit/6c39ee87e95df06194582a1809afd361b2483ae2
