### ISSUE TITLE
Pvalue of Lm for 0.0

### ISSUE THREAD

**Issue by anbai106** [ejolly/pymer4#90]
Hi,

I fit a simple linear regression model with Lm function;
```
model_all = Lm(component_name + " ~ age + sex + diagnosis", data=df)
model_all.fit(n_jobs=8)
```

```
Estimate    2.5_ci   97.5_ci      SE    DF  T-stat  P-val  Sig
Intercept  3148.194  3063.008  3233.380  43.434  1814  72.482    0.0  ***
age         -11.251   -12.416   -10.086   0.594  1814 -18.942    0.0  ***
sex         171.968   152.280   191.655  10.038  1814  17.132    0.0  ***
diagnosis   -89.521   -99.854   -79.188   5.269  1814 -16.992    0.0  ***
```

It worked but the output P-value is always 0.0. I think this is just a problem of the precision of the number for the output stats. I didn't find a solution to output more precise numbers.

I know that this means that the P-value is very low, but I still want the exact value. Can you help with this?

Thanks

**Comment by ejolly** [comment]
Hey @anbai106 the non-rounded estimates are available in `model_all.coefs`. The output from `.fit` and `.summary` [rounds everything to 3 decimal places](https://github.com/ejolly/pymer4/blob/master/pymer4/models/Lm.py#L450)
