### ISSUE TITLE
Problem with model fitting

### ISSUE THREAD

**Issue by pwsanders7** [ejolly/pymer4#95]
Hi, not sure if this is the best spot to leave this, but I am encountering an issue when trying to fit a model with the Lmer method.  I have attempted to specify a model using the following code:

`model = Lmer("PsychologicalDistressMean ~ SessionNumber + (SessionNumber|ClientId)", data = data)`
`print(model.fit())`

However, I am getting this error:
  File "c:\Analysis Files\pymer_test.py", line 24, in <module>
    print(model.fit())
  File "C:\Anaconda3\envs\pymer4\lib\site-packages\pymer4\models\Lmer.py", line 444, in fit
    if design_matrix:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

I have tried several solutions on my end.  All missing data has been removed, and the datatypes for all fields are set to float.  These are all valid columns in the dataframe.  The model without the Random Effects works fine with the Lm method.  Additionally, I have successfully run the model in Statsmodels.MixedLm.  I am familiar with this error in pandas generally, but unsure of why it would be arising in the current context, and have hit a wall in terms of how to deal with it.

Thanks!

**Comment by ejolly** [comment]
Hmm it's unclear without additional details about your data as to why this is happening. But given what line the error you're experiencing is on, it seems that you may be using an outdated version of `pymer`. Can you try updating to the latest version and seeing if it persists?

**Comment by JohannesWiesner** [comment]
I get the same error when running [this line](https://github.com/ejolly/pymer4/blob/b64273441f748e94b6b41946413c29ba982e9fc6/examples/example_01_basic_usage.py#L98) in the example script `example_01_basic_usage.py`. Interestingly, other runs of `print(model.fit()` before that line seem to work.

**Comment by mitjanikolaus** [comment]
I had the same problem. Following the suggestion from [this stackoverflow answer](https://stackoverflow.com/a/66981241/5346148), I changed the line 444 in `/pymer4/models/Lmer.py` to `if design_matrix is not None:`. 

That fixed it for me, hope it helps you as well!

**Comment by ejolly** [comment]
This should be fixed in the latest version of pymer4. Feel free to reopen if it isn't
