### ISSUE TITLE
Continuous interactions tables + plotting issue

### ISSUE THREAD

**Issue by shanaadise** [ejolly/pymer4#96]
Hello,

Is there an option to see estimates at specific values of contiguous variables for continuous * continuous interactions? Some other packages are able to output these estimates at -1SD, 0, and +1SD of the mean. I think this would be super helpful to see rather than to have to compute on your own.

Second, I am having an issue with using the command `model[brain].plot('reshist_addr1_coi_z_ed_nat', plot_ci=True, ylabel="predicted DV")`. The variable of interest is a continuous variable. However, the error message says: 

```
NotImplementedError                       Traceback (most recent call last)
<ipython-input-461-10c7c24b5875> in <module>
----> 1 model[brain].plot('reshist_addr1_coi_z_ed_nat', plot_ci=True, ylabel="predicted DV")
      2 

~/miniconda3/lib/python3.8/site-packages/pymer4/models/Lmer.py in plot(self, param, figsize, xlabel, ylabel, plot_fixef, plot_ci, grps, ax)
   1466             raise RuntimeError("Model must be fit before plotting!")
   1467         if self.factors:
-> 1468             raise NotImplementedError(
   1469                 "Plotting can currently only handle models with continuous predictors!"
   1470             )

NotImplementedError: Plotting can currently only handle models with continuous predictors!
```

**Comment by ejolly** [comment]
1) Thanks for the suggestion, I can look into this for future and I'll open a separate issue to track it. 
2) It looks like you fit your model with the `factors` keyword argument to `.fit` and currently plotting doesn't support models that contain _any_ factors.

**Comment by shanaadise** [comment]
I did not want to comment on the enhancement so I will write my comment here (in case it was already implemented). 

For context, here I am talking about estimating marginal means and pairwise comparisons. 

The EMMEANS package allows for the user to estimate marginal means and comparisons AT a level of the continuous IV. Is it possible to incorporate this into PYMER4? If it is already available, I apologize but the documentation did not seem to suggest that it was unless it is this option (which I do not think it is) `dof_asymptotic_at (int, optional) – at what number of observations to`

```
test(emmeans(m.EDA.hm, pairwise ~Condition*Time_sd, at = list(Time_sd = 2)))
test(emmeans(m.EDA.hm, pairwise ~Condition*Time_sd, at = list(Time_sd = -2)))
test(emmeans(m.EDA.hm, pairwise ~Condition*Time_sd, at = list(Time_sd = -0)))
```
